### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by dhuppenkothen** [AstroHackWeek/AstroHackWeek2020#1]
Here are the milestones for making AHW 2020 happen!

- [ ] Initial telecon with SOC 
- [ ] Website ready 
- [ ] Application form ready before Christmas (?)
- [ ] Application Open at AAS
- [ ] Application Deadline Mar 15
- [ ] First participant selection Mar 31 + funding ready 
- [ ] Participant list ready mid-May
- [ ] AHW August/September
